### PR TITLE
Replace project avatars

### LINKED ISSUE #131: Replace Dicebear with static generated images
I really like the project list display with image icons in the view. However, not all projects will have this. We are using the GitHub supplied avatar_url for projects with a connected remote_repo, but for others, we need something generative or a default image.

For now, I'm using Dicebear hosted images, which ultimately are SVGs currently.

In the future, we probably want these on our domain, and it wouldn't be hard to generate these and serve the statically. We probably want to:

- Generate 50-10 images and store them in our repo
- Reference these files by some sort of hashing. `{project.pk % 50}.svg` even
- Tune the look and feel of the icons, I didn't do much here yet. We could use initials too.

We might also want to do this for default _user_, _team_, and _organization_ images. Right now we rely on gravatar for organizations (weird), lots of users have the empty face icon, and we have no visual identifier for teams besides a name.

### Update

The PR attached here implements a nice replacement for projects without remote repo avatar URLs, but it did overlook some caching attacks. With an API v3 change, it would be possible to do this all from the front end side instead. I'll wait on this to continue, if someone wants to jump in on that change (it should be small, but I haven't looked yet)

- https://github.com/readthedocs/readthedocs.org/issues/10513

### PR DESCRIPTION
**Pull request by agjohnson**
- [x] Fix URL for web component styles and avatar image
- [x] Create a 100x100px image, mapped to our current color scheme colors on the dashboard. This creates a lot of nice variance in colors and matches the look and feel in addition.
- [x] Resize to something easy for bitwise hashing math, 128x128?
- [x] Find the right pattern for avoiding inline styles and background positioning
- [x] Fix positioning on the project header, it's out of place now

----

- Resolves #131

### CODE REVIEW

**Comment by agjohnson** [comment]
Image

**Comment by agjohnson** [comment]
I worked through patterns for attributes, using a static URL for the image, updated the underlying sprite, and fixed an issue on the project header.

With the new sprite, the dashboard looks like this now:

image

The image is a palette mapped image, using colors from the FUI base color scheme. If this looks too busy, I can try a palette mapped image using less of the colors.

**Comment by agjohnson** [comment]
I like the look of the 8x8 pixel avatar, but would say the 4x4 looks more like it is a generated icon. The color limited color scheme works much nicer too, all the colors are prominent in the dashboard already.

I think my favorite is 4x4 pixels, limited FUI color palette:

image

**Review by humitos — COMMENTED** [review]
Looks good to me. The only thing I would change is the background image used. I'd propose to generate one ourselves in some random way by taking a color palette from https://colorhunt.co/ that looks nice.

**Comment by agjohnson** [comment]
I am already using the same color palette as FUI. What is the concern around generating an image vs processing a photo?

**Review by ericholscher — APPROVED** [review]
🚢

**Pull request merged**
