### PR TITLE
Try djlint instead of djhtml

### LINKED ISSUE #329: Lint: try swapping to djlint
We are currently using djhtml here for html formatting. This package only does part of what djlint does, but was providing nicer html formatting when I first tried both. I did try djlint recently and the formatting was mostly okay. I think we could swap to djlint if we wanted to, as djlint does have some more checks on templates.

Some things to evaluate:

- [ ] Template indentation and formatting looks okay/better with djlint?
- [ ] djlint catches easy to miss things like multiline, single line comments (`{# #}`), maybe HTML errors?
- [ ] djlint catches/fixes other issues?

This will be a disruptive change, so would hopefully be an obvious choice after playing with djlint a bit more.

### PR DESCRIPTION
**Pull request by agjohnson**
Djhtml is inconsistent and doesn't provide any linting checks. Running djlint instead, and through pre-commit on a per-file basis, gives a fairly easy way to migrate to stronger formatting/linting on template code.

- Fixes #329

### CODE REVIEW

**Comment by agjohnson** [comment]
If we want to enable this, it should only run on future edits to templates. The reformatting is more consistent than djhtml, but the linting rules are quite helpful and enforce our development rules. However, this would involve fixing some unrelated template issues fairly frequently. Here's an example of fixes:

```
readthedocsext/theme/templates/includes/footer.html

T002 75:34 Double quotes should be used in tags. {% trans 'Version' %
H022 77:16 Use HTTPS for external links. <a href="http://docs
T002 86:34 Double quotes should be used in tags. {% trans 'Language'
D018 90:18 (Django) Internal links should use the {% url ... %} pattern. <form action="/i18n/
H006 144:16 Img tag should have height and width attributes. <img class="ui tiny
H006 153:16 Img tag should have height and width attributes. <img class="ui tiny
H006 162:16 Img tag should have height and width attributes. <img class="ui tiny
H006 171:16 Img tag should have height and width attributes. <img class="ui tiny
H006 180:16 Img tag should have height and width attributes. <img class="ui tiny
H006 189:16 Img tag should have height and width attributes. <img class="ui tiny
```

We could start with reformatting and introduce rules next, tune rules back, or just accept that the edits are all really minor and go 100% on djlint from the start.

**Comment by ericholscher** [comment]
I'm 👍 on moving forward here. It would be really nice if there was a black-style auto-formatter, so we could format everything once, and then move forward with stricter rules. I really dislike hitting random linter issues on every PR.

**Comment by agjohnson** [comment]
To clarify, djhtml is already doing autoformatting on templates, it just isn't as strict as djlint. djlint has more opinionated formatting and has the option of strict rule checks in addition, which is the stronger upgrade. The autoformatting will only change slightly -- indentation is more opinionated and attribute wrapping is more frequent.

I might be wrong about how this will work, but if we're okay fixing template issues a file at a time, I think the configuration here works. That is, when a template file is touched next, djlint will update the whole file. We will have to tune ignore rules as we go, which is fine, and perhaps just punt on some rules for now too, which I would say is also fine.

**Comment by ericholscher** [comment]
Yea, I'm fine being pretty aggressive with ignore rules, and then removing them as a later step.

**Review by ericholscher — APPROVED** [review]
I'm fine to this try 👍

**Pull request merged**
