### PR TITLE
Build list: protect us against builds without versions

### LINKED ISSUE #412: `NoReverseMatch` when hitting builds listing page
Go to https://app.readthedocs.org/projects/pycampes/builds/ and/or https://app.readthedocs.org/projects/pygsp2/builds/ and you will get a 500.

Sentry error: https://read-the-docs.sentry.io/issues/5564576585/

Front logo [Front conversations](https://app.frontapp.com/open/top_11t9zb)

### PR DESCRIPTION
**Pull request by humitos**
Closes #412

### CODE REVIEW

**Review by agjohnson — APPROVED** [review]
This looks good :+1:

**Comment by agjohnson** [comment]
Note though, lint failed on `load` rules.

**Comment by humitos** [comment]
Lint fails due to

```
readthedocsext/theme/templates/builds/partials/build_list.html
───────────────────────────────────────────────────────────────────────────────
@@ -41,7 +41,7 @@

       {% blocktrans trimmed asvar text_retry %}
         Rebuild version
       {% endblocktrans %}
-      <readthedocs-menu-build-rebuild
+      <readthedocs-menu -build-rebuild
                         class="ui button"
                         url="{% url "projects-versions-builds-list" object.project.slug object.version.slug %}"
                         csrf-token="{{ csrf_token }}"
```

but it doesn't make sense. How I can do to skip it?

**Comment by humitos** [comment]
> but it doesn't make sense. How I can do to skip it?

I skipped it by using `djlint:off` for now.

**Comment by agjohnson** [comment]
We need another pattern here for the linting error

https://github.com/readthedocs/ext-theme/blob/4b04cca66bbc8604229a56a46286d389cb1869f1/.djlintrc#L6

**Pull request merged**
